// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkplwGKlahL_HWb_sSG2u4HKPXPdvvX-8',
    appId: '1:789414248250:web:6f3e3912ff78b330629a03',
    messagingSenderId: '789414248250',
    projectId: 'exploreug-8970b',
    authDomain: 'exploreug-8970b.firebaseapp.com',
    storageBucket: 'exploreug-8970b.appspot.com',
    measurementId: 'G-Y6FTT61VY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzVVmGV8Zr-GsYK1Wnl1K_Nl1Rd94phw',
    appId: '1:789414248250:android:5ab7424816df1062629a03',
    messagingSenderId: '789414248250',
    projectId: 'exploreug-8970b',
    storageBucket: 'exploreug-8970b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZMqCytdOJIZyr8FMOA50laKIGaQn5Eo',
    appId: '1:789414248250:ios:85ee65f571c79b12629a03',
    messagingSenderId: '789414248250',
    projectId: 'exploreug-8970b',
    storageBucket: 'exploreug-8970b.appspot.com',
    iosBundleId: 'com.example.exploreUganda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZMqCytdOJIZyr8FMOA50laKIGaQn5Eo',
    appId: '1:789414248250:ios:85ee65f571c79b12629a03',
    messagingSenderId: '789414248250',
    projectId: 'exploreug-8970b',
    storageBucket: 'exploreug-8970b.appspot.com',
    iosBundleId: 'com.example.exploreUganda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkplwGKlahL_HWb_sSG2u4HKPXPdvvX-8',
    appId: '1:789414248250:web:04ddfbaaf0a96392629a03',
    messagingSenderId: '789414248250',
    projectId: 'exploreug-8970b',
    authDomain: 'exploreug-8970b.firebaseapp.com',
    storageBucket: 'exploreug-8970b.appspot.com',
    measurementId: 'G-NXC3GR84TY',
  );
}
